databases:
  - name: librarysystemdb
    plan: free
    databaseName: librarysystem
    user: hamynhu

services:
  - type: web
    plan: free
    name: LibrarySystem
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn LibrarySystem.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: librarysystemdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
