# Generated by Django 5.2.2 on 2025-06-09 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asiakas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(default='', max_length=100)),
                ('puhelin', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['nimi'],
            },
        ),
        migrations.CreateModel(
            name='Kirja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otsikko', models.CharField(default='', max_length=100)),
                ('kirjoittaja', models.CharField(default='', max_length=50)),
                ('isbn', models.CharField(default='', max_length=13)),
                ('saatavissa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['otsikko'],
            },
        ),
        migrations.CreateModel(
            name='Lainaus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lainattu_aika', models.DateTimeField(auto_now_add=True)),
                ('palautettu_aika', models.DateTimeField(blank=True, null=True)),
                ('asiakas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asiakas')),
                ('kirja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kirja')),
            ],
            options={
                'ordering': ['kirja'],
            },
        ),
    ]
