# Generated by Django 5.2.2 on 2025-06-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lainaus',
            name='lainattu_aika',
            field=models.DateTimeField(),
        ),
    ]
